version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Database=allowance_tracker;Username=postgres;Password=${DB_PASSWORD}
      - Jwt__SecretKey=${JWT_SECRET_KEY}
      - Jwt__Issuer=AllowanceTracker
      - Jwt__Audience=AllowanceTracker
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=allowance_tracker
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
