name: AllowanceTracker

options:
  bundleIdPrefix: app.earnandlearn
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  createIntermediateGroups: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 17.0

targets:
  AllowanceTracker:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - "Tests/**"
          - "UITests/**"
          - "Package.swift"
          - "project.yml"
          - "README.md"
          - "*.md"
      - path: Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.earnandlearn.ios
        INFOPLIST_FILE: App/Info.plist
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        ENABLE_TESTABILITY: true
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 5L2J3MYB5N
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    entitlements:
      path: App/AllowanceTracker.entitlements
    scheme:
      testTargets:
        - AllowanceTrackerTests
        - AllowanceTrackerUITests
      gatherCoverageData: true

  AllowanceTrackerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests
    dependencies:
      - target: AllowanceTracker
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.earnandlearn.ios.tests
        TARGETED_DEVICE_FAMILY: "1,2"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/AllowanceTracker.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/AllowanceTracker"
        BUNDLE_LOADER: "$(TEST_HOST)"
        GENERATE_INFOPLIST_FILE: YES
    scheme:
      gatherCoverageData: true

  AllowanceTrackerUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - UITests
    dependencies:
      - target: AllowanceTracker
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.earnandlearn.ios.uitests
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: AllowanceTracker
    scheme:
      gatherCoverageData: true

schemes:
  AllowanceTracker:
    build:
      targets:
        AllowanceTracker: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - AllowanceTrackerTests
        - AllowanceTrackerUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
